// import './day_1/solution.ts';
// import './day_2/solution.ts';
// import './day_3/solution.ts';
// import './day_4/solution.ts';
// import './day_5/solution.ts';
// import './day_6/solution.ts';
// import './day_7/solution.ts';
// import './day_8/solution.ts';
// import './day_9/solution.ts';
import './day_10/solution.ts';
